"""Generate the reference docs (docs/reference/*.md) straight from the live registries.

So the documentation can never drift from what is actually registered: `reel reference -o docs/reference`.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from reel.core.catalog import CATALOG, Catalog
from reel.core.manifest import describe
from reel.core.rig import CHANNELS


def _md_table(header: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    for r in rows:
        out.append("| " + " | ".join(c.replace("|", "\\|").replace("\n", " ") for c in r) + " |")
    return "\n".join(out)


def _params_table(params: list[dict[str, Any]]) -> str:
    if not params:
        return "_no parameters_\n"
    rows = []
    for p in params:
        t = str(p.get("type", ""))
        if "enum" in p:
            t = " | ".join(f"`{v}`" for v in p["enum"])  # the table writer escapes the pipes
        d = p.get("default", "—" if not p.get("required") else "**required**")
        lim = ""
        if "minimum" in p or "maximum" in p:
            lim = f" ({p.get('minimum', '')}…{p.get('maximum', '')})"
        rows.append(
            [
                f"`{p['name']}`",
                t + lim,
                f"`{d}`" if d not in ("—", "**required**") else str(d),
                p.get("description", ""),
            ]
        )
    return _md_table(["param", "type", "default", "meaning"], rows) + "\n"


def actions_md(cat: Catalog) -> str:
    rows = describe("action", cat, builtin_only=True)
    out = ["# Actions", "", "_Generated by `reel reference` from the live registry._", ""]
    by_cat: dict[str, list[dict[str, Any]]] = {}
    for r in rows:
        by_cat.setdefault(str(r.get("category", "misc")), []).append(r)
    out.append(
        _md_table(
            ["action", "category", "summary"],
            [
                [f"[`{r['name']}`](#{r['name']})", str(r.get("category", "")), r["summary"]]
                for r in rows
            ],
        )
    )
    out.append("")
    for category, items in sorted(by_cat.items()):
        out.append(f"## {category.capitalize()}\n")
        for r in items:
            out.append(f"### {r['name']}\n")
            out.append(f"{r['summary']}\n")
            facts = []
            if r.get("moves_root"):
                facts.append("moves the character")
            if r.get("min_duration"):
                facts.append(f"min {r['min_duration']:g}s")
            if r.get("default_duration"):
                facts.append(f"typical {r['default_duration']:g}s")
            if facts:
                out.append("_" + ", ".join(facts) + "_\n")
            out.append(_params_table(r.get("params", [])))
    return "\n".join(out)


def backgrounds_md(cat: Catalog) -> str:
    rows = describe("background", cat, builtin_only=True)
    out = [
        "# Background templates",
        "",
        "_Generated by `reel reference` from the live registry._",
        "",
    ]
    out.append(
        "Every template accepts `time_of_day` (`dawn|day|dusk|night`), `mood` (`neutral|warm|cool|dramatic|playful|gloomy`) and `density` (0..1); "
        "the universal character slots `left center right far_left far_right off_left off_right` always exist.\n"
    )
    for r in rows:
        out.append(f"## {r['name']}\n")
        out.append(f"{r['summary']}\n")
        if r.get("slots"):
            out.append("**slots:** " + ", ".join(f"`{s}`" for s in r["slots"]) + "\n")
        extra = [
            p for p in r.get("params", []) if p["name"] not in ("time_of_day", "mood", "density")
        ]
        out.append(_params_table(extra))
    return "\n".join(out)


def simple_md(title: str, kind: str, cat: Catalog, extra_cols: tuple[str, ...] = ()) -> str:
    rows = describe(kind, cat, builtin_only=True)
    header = ["name", "summary", *extra_cols]
    body = [
        [f"`{r['name']}`", r["summary"], *[str(r.get(c, "")) for c in extra_cols]] for r in rows
    ]
    return (
        f"# {title}\n\n_Generated by `reel reference` from the live registry._\n\n"
        + _md_table(header, body)
        + "\n"
    )


def _words(row: dict[str, Any], limit: int = 12) -> str:
    """What a script may call a library asset: its tags (its own name left out), the Latin ones first, then the Indic ones."""
    own = str(row["name"]).replace("_", " ")
    have = set(row.get("tags", []))
    tags = [
        t for t in row.get("tags", []) if t != own and not (t.endswith("s") and t[:-1] in have)
    ]  # plurals fold away
    ordered = [t for t in tags if t.isascii()] + [t for t in tags if not t.isascii()]
    return ", ".join(ordered[:limit])


def assets_md(cat: Catalog) -> str:
    """The built-in asset library: every character, object and place that ships (the user's own folders are not listed)."""
    from reel.core.manifest import build_manifest

    m = build_manifest(cat, builtin_only=True)
    sections = (
        ("Characters", "characters[].archetype", [r for r in m["archetypes"] if r.get("library")]),
        ("Objects", "scenes[].objects[].asset", m["objects"]),
        (
            "Places",
            "scenes[].background.template",
            [r for r in m["backgrounds"] if r.get("library")],
        ),
    )
    out = [
        "# The built-in asset library",
        "",
        "_Generated by `reel reference` from the live registries. How to add your own: [assets.md](../assets.md)._",
        "",
        "`size` is the height as a share of a person (1 = a person); `recolour` are the colours a spec's `palette` can change; "
        "`a script can say` are the words the planners match (English, Hindi and Hinglish).",
        "",
    ]
    for title, used_as, rows in sections:
        out += [f"## {title} ({len(rows)})", "", f"Used as `{used_as}`.", ""]
        body = [
            [
                f"`{r['name']}`",
                r["summary"],
                _words(r),
                f"{r['size']:g}" if "size" in r and title != "Places" else "",
                ", ".join(f"`{x}`" for x in r.get("roles", [])),
            ]
            for r in rows
        ]
        out += [_md_table(["name", "what it is", "a script can say", "size", "recolour"], body), ""]
    return "\n".join(out)


def channels_md() -> str:
    rows = [
        [f"`{c.name}`", c.group, c.unit, f"{c.default:g}", f"{c.lo:g} … {c.hi:g}", c.doc]
        for c in CHANNELS.values()
    ]
    return (
        "# Rig channels\n\n_Generated by `reel reference`._\n\n"
        "The animatable degrees of freedom of the character rig.  Angles are degrees: 0 = limb hangs straight down, "
        "+90 = pointing forward (+x), +180 = straight up; knee/elbow flexion is always >= 0.  Prop attachment weights are "
        "extra channels named `prop:<name>` (1 = held/worn, 0 = on the floor).\n\n"
        + _md_table(["channel", "group", "unit", "default", "range", "meaning"], rows)
        + "\n"
    )


def easings_md(cat: Catalog) -> str:
    rows = [
        [f"`{n}`", str(dict(e.meta).get("summary", ""))]
        for n, e in ((e.name, e) for e in cat.easings.entries())
    ]
    return (
        "# Easings\n\n_Generated by `reel reference`._\n\n"
        + _md_table(["name", "behaviour"], rows)
        + "\n"
    )


def write_reference(out_dir: Path, catalog: Catalog | None = None) -> list[Path]:
    cat = catalog or CATALOG
    out_dir.mkdir(parents=True, exist_ok=True)
    files = {
        "actions.md": actions_md(cat),
        "backgrounds.md": backgrounds_md(cat),
        "styles.md": simple_md("Style packs", "style", cat),
        "transitions.md": simple_md("Transitions", "transition", cat),
        "camera.md": simple_md("Camera moves", "camera_move", cat, ("from_to",)),
        "captions.md": simple_md("Caption styles", "caption_style", cat),
        "archetypes.md": simple_md("Character archetypes", "archetype", cat),
        "assets.md": assets_md(cat),
        "props.md": simple_md("Props", "prop", cat),
        "sfx.md": simple_md("Sound effects", "sfx", cat),
        "easings.md": easings_md(cat),
        "channels.md": channels_md(),
    }
    paths = []
    for name, text in files.items():
        p = out_dir / name
        p.write_text(text)
        paths.append(p)
    index = [
        "# Reference",
        "",
        "Generated from the live registries by `reel reference -o docs/reference`.",
        "",
    ]
    index += [f"- [{n[:-3].replace('_', ' ')}]({n})" for n in files]
    (out_dir / "README.md").write_text("\n".join(index) + "\n")
    return paths
