"""Background templates: parameterised scenes the LLM/user fill in, the template adapts to.

`manifest.json` next to this file is the machine-readable catalog (generated by
`reel manifest -o src/reel/templates/manifest.json`) that the script->JSON prompt embeds, so
the model only ever picks things that exist.
"""

import importlib
import pkgutil

from reel.templates.base import BackgroundDef, BgParams, BuildContext, register_background

__all__ = ["BackgroundDef", "BgParams", "BuildContext", "register_background"]

for _m in pkgutil.iter_modules(__path__):
    if not _m.name.startswith("_") and _m.name not in ("base", "palette"):
        importlib.import_module(f"{__name__}.{_m.name}")
